### ISSUE TITLE
[Event Handlers] syntax example for loading multiple `requiredEntities` for single event

### ISSUE THREAD

**Issue by WooSungD** [enviodev/docs#172]
Currently there's no example of this in the docs.

For example:

Config:
```yaml
- event: Sync(uint256 reserve0, uint256 reserve1)
   requiredEntities:
    - name: Token
      labels: [token0, token1]
    - name: Pool
      labels: [existingPool]
```

Schema:
```graphql
type Token @entity {
  # token address
  id: ID!

  # mirrored from the smart contract
  symbol: String!
  name: String!
  decimals: BigInt!
  price: BigInt!
  derivedETH: BigInt!
}

# Data accumulated and condensed into day stats for each exchange
type Pool @entity {
  id: ID! # block number
  # mirrored from the smart contract
  token0: Token!
  token1: Token!
  stable: Boolean!
  reserve0: BigInt!
  reserve1: BigInt!
  # PoolDayData: PairDayData! @derivedFrom(field: "pair")
}
```

Event Handlers:
```typescript
PoolContract_Sync_loader(({ event, context }) => {
  context.Pool.existingPoolLoad(event.srcAddress.toString(), {
    loaders: { loadToken0: true, loadToken1: true },
  });
});

PoolContract_Sync_handler(({ event, context }) => {
  let current_pool = context.Pool.existingPool;

  if (current_pool) {
    let token_0 = context.Pool.getToken0(current_pool);
    let token_1 = context.Pool.getToken1(current_pool);
```
