### ISSUE TITLE
If we add an `rpc` field under each Network object in the YAML config, does that mean we're no longer using HyperSync?

### ISSUE THREAD

**Issue by PaulRBerg** [enviodev/docs#655]
I was looking at these docs: [Improving resilience with RPC fallback](https://docs.envio.dev/docs/HyperIndex/hypersync#improving-resilience-with-rpc-fallback).

It's not clear to me what happens if we add an `rpc` field like this:

```yaml
name: Greeter
description: Greeter indexer
networks:
  - id: 137 # Polygon
+   # Short and simple
+   rpc: https://eth-mainnet.your-rpc-provider.com?API_KEY={ENVIO_MAINNET_API_KEY}
```

Does this field completely override HyperSync, i.e., HyperSync will no longer be used. Or will it be used as a fallback?

I can see that when I add multiple `rpc`, there is a `for: fallback` thingy, but I'm not sure if the same setting applies when I am only defining `rpc`.
